export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const LOGOUT = "LOGOUT";

export const GET_BOARDS_REQUEST = "GET_BOARDS_REQUEST";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";
export const GET_BOARDS_FAILED = "GET_BOARDS_FAILED";

export const POST_BOARD_REQUEST = "POST_BOARD_REQUEST";
export const POST_BOARD_SUCCESS = "POST_BOARD_SUCCESS";
export const POST_BOARD_FAILED = "POST_BOARD_FAILED";

export const GET_BOARDBY_ID_REQUEST = "GET_BOARDBY_ID_REQUEST";
export const GET_BOARDBY_ID_SUCCESS = "GET_BOARDBY_ID_SUCCESS";
export const GET_BOARDBY_ID_FAILED = "GET_BOARDBY_ID_FAILED";

export const EDIT_BOARD_REQUEST = "EDIT_BOARD_REQUEST";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_FAILED = "EDIT_BOARD_FAILED";

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILED = "DELETE_BOARD_FAILED";

export const GET_LISTS_REQUEST = "GET_LISTS_REQUEST";
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAILED = "GET_LISTS_FAILED";

export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILED = "POST_LIST_FAILED";

export const EDIT_LIST_REQUEST = "EDIT_LIST_REQUEST";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";
export const EDIT_LIST_FAILED = "EDIT_LIST_FAILED";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAILED = "DELETE_LIST_FAILED";
